spring:
  redis:
    password: icepoint123
    database: 1
  servlet:
    multipart:
      #是否开启上传文件配置，如果采用的是CommonsMultipartResolver解析文件，则需要关闭Spring Boot默认上传文件入口
      enabled: true
      #文件上传临时保存位置，没有写入最终保存位置时存放的位置
      location: /data/
      #上传单个文件最大大小
      max-file-size: 1MB
      #上传一组文件最大大小
      max-request-size: 5MB
      #是否延迟解析，相当于懒加载
      resolve-lazily: false
      #文件大小阈值，当大于这个阈值时将写入到磁盘，否则存在内存中，默认为0
      file-size-threshold: 0